Updates to risk block and codelists
open-contracting-extensions/ocds_riskAllocation_extension pull request #2
Opened 2017-03-28 14:09 UTC by duncandewhurst

Make riskCategory an open codelist and update codes and definitions in
line with consultation feedback. Remove likelihood and fiscalImpact
properties. Remove shared code from riskAllocation codelist and replace
with 'undefined'

2017-03-28 16:11 UTC, timgdavies requested changes
To fit with 1.1 we need to:

(1) Remove the merge strategies;

(2) Include 

``` "codelist":"codelist.csv", 
      "openCodelist":false 
```
properties against each field with codes, and remove the enums.

2017-03-29 09:27 UTC, duncandewhurst commented
@timgdavies I've made those updates in [452b123](https://github.com/open-contracting/ocds-riskAllocation-extension/pull/2/commits/452b123742cd72ce2f4ef7d1218fb45f7e7c4b3f) and also update the riskCategory codelist in line with Abdou's latest email.

Ok to merge now?

2017-03-29 09:30 UTC, timgdavies commented on release-schema.json
> +          ]
add

```json
"codelist":"riskCategory.csv",
"openCodelist":false
```

2017-03-29 09:30 UTC, timgdavies commented on release-schema.json
> +		"openCodelist": "false"
Add

```json
"codelist":"riskAllocation.csv",
"openCodelist":false
```

(note no quotes around false)

2017-03-29 09:31 UTC, timgdavies requested changes
Small tweaks still needed to schema I'm afraid. Check the 1.1 scheme for the syntax for codelist markup etc. http://standard.open-contracting.org/1.1-dev/en/release-schema.json

2017-03-29 09:46 UTC, duncandewhurst commented
@timgdavies thanks - updated inline with your comments, except for riskCategory which is an open codelist so have set openCodelist = true

2017-03-29 09:59 UTC, timgdavies approved these changes

2017-03-29 09:59 UTC, merged